# Generated by Django 5.0.6 on 2025-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_category_student_segments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='segments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
